### ISSUE TITLE
Doesn't Download Correctly

### ISSUE THREAD

**Issue by ghost** [BaliBalo/twitterVolumeControl#1]
Sorry, forgot proof

https://gyazo.com/253d66c2be7e0776d4684c3b518efedd

**Comment by BaliBalo** [comment]
Thanks a lot for the feedback, I forgot to include the icons when updating on the chrome webstore. I just re-uploaded a correct version so it should be fixed when it get published in a few minutes.

**Comment by BaliBalo** [comment]
So the new version still haven't been published, I thought it was faster. Hopefully it gets done during the day.
